---

- hosts: test_instances
  become: yes
  gather_facts: no
  tasks:

    - name: Ensure python requirements are installed
      raw: dnf -y install python3 python3-dnf
      register: python_reqs
      changed_when: "'Nothing to do' not in python_reqs.stdout"

- hosts: test_instances
  vars_files:
    - vars.yml
  become: yes
  roles:
    - osbuild
