---

- name: Set default facts
  set_fact:
    osbuild_repo: "{{ osbuild_repo | default('https://github.com/osbuild/osbuild') }}"
    osbuild_version: "{{ osbuild_version | default('master') }}"
    osbuild_ref: "{{ osbuild_ref | default('+refs/pull/*:refs/heads/*') }}"
    osbuild_composer_repo: "{{ osbuild_composer_repo | default('https://github.com/osbuild/osbuild-composer') }}"
    osbuild_composer_version: "{{ osbuild_composer_version | default('master') }}"
    osbuild_composer_ref: "{{ osbuild_composer_ref | default('+refs/pull/*:refs/heads/*') }}"
    cockpit_composer_repo: "{{ cockpit_composer_repo | default('https://github.com/osbuild/cockpit-composer') }}"
    cockpit_composer_version: "{{ cockpit_composer_version | default('master') }}"
    cockpit_composer_ref: "{{ cockpit_composer_ref | default('+refs/pull/*:refs/heads/*') }}"

- name: Dump what we will be doing
  debug:
    msg: |
      Current deployment plan:

      osbuild_repo: {{ osbuild_repo }}
      osbuild_version: {{ osbuild_version }}
      osbuild_ref: {{ osbuild_ref }}

      osbuild_composer_repo: {{ osbuild_composer_repo }}
      osbuild_composer_version: {{ osbuild_composer_version }}
      osbuild_composer_ref: {{ osbuild_composer_ref }}

      {% if install_cockpit_composer_from_git %}
      cockpit_composer_repo: {{ cockpit_composer_repo }}
      cockpit_composer_version: {{ cockpit_composer_version }}
      cockpit_composer_ref: {{ cockpit_composer_ref }}
      {% else %}
      cockpit_composer_version: from Fedora's repositories
      {% endif %}

- name: Set a password for the default user
  user:
    name: "{{ ansible_ssh_user }}"
    password: "{{ password_hashes[ansible_ssh_user] }}"
    update_password: always

- name: Install ssh keys
  authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ item }}"
  loop: "{{ valid_ssh_keys }}"
  loop_control:
    label: "{{ item.split(' ') | last }}"

- import_tasks: install.yml

- import_tasks: test_api_server.yml

- import_tasks: test_integration.yml
  when: run_integration_tests | bool
