---

- name: Install additional packages
  dnf:
    name:
      - cockpit-composer
      - composer-cli
    state: present
  become: yes
  when: "'composer' in group_names"

- name: Stop the osbuild default worker service if it has started
  systemd:
    name: osbuild-worker@1.service
    state: stopped
    masked: yes
  ignore_errors: yes
  become: yes

- name: Disable services
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
  become: yes
  ignore_errors: yes
  loop:
    - cockpit-socket
    - osbuild-composer.socket
    - osbuild-rcm.socket
    - osbuild-composer.service
    - osbuild-remote-worker.socket

- name: Start osbuild-composer's remote worker socket
  systemd:
    name: osbuild-remote-worker.socket
    state: started
    enabled: yes
    daemon-reload: yes
  become: yes
  when: "'composer' in group_names"

- name: Start remote workers
  systemd:
    name: osbuild-remote-worker@composer:8700
    state: started
    enabled: yes
  become: yes
  when: "'workers' in group_names"

- name: Enable cockpit
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  become: yes
  loop:
    - cockpit.socket
  when: "'composer' in group_names"

# composer-cli seems to exit with a return code of 1 when everything is okay.
- name: Test composer-cli
  command: composer-cli status show
  become: yes
  register: composer_cli_test
  failed_when: "'API server status' not in composer_cli_test.stdout"
  when: "'composer' in group_names"

- name: Show output
  debug:
    var: composer_cli_test.stdout
  when: "'composer' in group_names"